// Build-time manifest of pre-generated narration MP3s.
//
// Scans public/audio/kristy/ and writes src/lib/audioManifest.js:
// a Set of "voice/sha256(voice|text)[:32]" entries for every staged clip.
//
// Why: ~80% of spoken strings have no pre-generated clip yet. For those,
// the runtime used to fetch the MP3 URL (which the SPA fallback answers
// with index.html + HTTP 200!) and POST a safety net that 404s in prod,
// burning ~a second of dead air per utterance before the Web Speech
// fallback kicked in. With the manifest, narration.js skips the MP3 attempt
// for hashes that don't exist and goes straight to speech.
//
// Runs automatically via the `prebuild` npm script, so Cloudflare Pages
// always ships a manifest that matches the committed clips. Safe to run
// by hand: `node scripts/build_audio_manifest.mjs`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const audioDir = path.join(root, 'public', 'audio');
const outFile = path.join(root, 'src', 'lib', 'audioManifest.js');

const entries = [];
for (const voice of ['kristy']) {
  const dir = path.join(audioDir, voice);
  if (!fs.existsSync(dir)) continue;
  for (const f of fs.readdirSync(dir)) {
    if (f.endsWith('.mp3')) entries.push(`${voice}/${f.slice(0, -4)}`);
  }
}

const body = `// AUTO-GENERATED by scripts/build_audio_manifest.mjs — do not edit by hand.
// "voice/hash" for every pre-generated narration MP3 in public/audio/.
// Regenerated on every build (prebuild); committed so local dev matches.
export const AUDIO_MANIFEST = new Set(${JSON.stringify(entries)});
export const AUDIO_MANIFEST_GENERATED = ${JSON.stringify(new Date().toISOString())};
`;
fs.writeFileSync(outFile, body);
console.log(`[audio_manifest] ${entries.length} clips -> src/lib/audioManifest.js`);
