// Stage pre-generated ElevenLabs MP3s into dist/audio/ so the app serves
// them same-origin (no R2 bucket needed). Source of truth for what exists
// locally: ~/workspace/reading-ladder-audio/{sarah,brian}/*.mp3
// (see scripts/generate_audio.py + audio_manifest.json).
//
// Idempotent: copies only files that are missing or differ in size; skips
// gracefully when the audio folder is absent (CI), so `npm run build` still
// works there. The remaining clips are generated by re-running
// scripts/generate_audio.py once ElevenLabs quota is available — this script
// picks up whatever exists at build time.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const VOICES = ['sarah', 'brian'];
const SRC = path.join(os.homedir(), 'workspace', 'reading-ladder-audio');
const DIST = path.join(path.dirname(new URL(import.meta.url).pathname), '..', 'dist', 'audio');

let staged = 0;
for (const voice of VOICES) {
  const srcDir = path.join(SRC, voice);
  if (!fs.existsSync(srcDir)) {
    console.log(`[stage_audio] no local audio for "${voice}" at ${srcDir} — skipping`);
    continue;
  }
  const dstDir = path.join(DIST, voice);
  fs.mkdirSync(dstDir, { recursive: true });
  for (const f of fs.readdirSync(srcDir)) {
    if (!f.endsWith('.mp3')) continue;
    const src = path.join(srcDir, f);
    const dst = path.join(dstDir, f);
    const { size } = fs.statSync(src);
    let copy = true;
    if (fs.existsSync(dst) && fs.statSync(dst).size === size) copy = false;
    if (copy) {
      fs.copyFileSync(src, dst);
      staged++;
    }
  }
}
console.log(`[stage_audio] staged ${staged} new clip(s) into dist/audio/`);
